modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LGPLv3" # Want to make your mod open source? Check out https://choosealicense.com/!
issueTrackerURL = "https://github.com/MaxNeedsSnacks/roadrunner/issues"

[[mods]]
modId = "roadrunner"

version = "${version}"
displayName = "Meep Meep! (Road Runner)"

description = '''
An unofficial fork of the popular optimisation mod Lithium, made for the Forge mod loader.
'''

[[dependencies.roadrunner]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadrunner]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"